server:
  error:
    include-message: always
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: shermatov
    password: aibeksher
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true

  main:
    web-application-type: servlet

